function value = getViewAnimationInput
value.file = '';
value.deltaT = 0.1;
value.thicknessMultiplier = 1;
value.refractoryDuration = 5;
value.excitatoryProb = 0.01;
value.inhibitoryProb = 0;
value.attenuationProb = 0.01;
value.showTimes = false;
value.colours.soma = [0.5 0 0.5]; % purple
value.colours.axon = [0 0 1]; % blue
value.colours.dendrite = [0 1 0]; % green
value.colours.active = [1 0 0]; % red
value.colours.refractory = [1 0.5 0]; % orange